### PR TITLE
Add svg

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
Addressed https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide/issues/79#issuecomment-1760052189

### CODE REVIEW

**Comment by zacharyDez** [comment]
@abarciauskas-bgse , is there any way to add the draw file? It might not be if you did not save it locally or have the premium version. @kcarini was talking about making some modifications for the release.

**Comment by abarciauskas-bgse** [comment]
@zacharyDez added it, do we want both svg and excalidraw? (sidebar: i'm still trying to figure out how to manage diagrams in excalidraw since all i can tell is that I have one canvas in each browser session)

**Comment by zacharyDez** [comment]
@abarciauskas-bgse, ya, I think it is their main differentiator between the free and premium versions. I usually download the excalidraw file locally to be able to edit it later. Keeping it in version control will make our lives easier in the long run! 

Appreciate it!! 🙏

**Review by zacharyDez — APPROVED** [review]

**Comment by zacharyDez** [comment]
closes #79

**Pull request merged**
